add_newline = true
command_timeout = 2000

format = """\
[╭╴](fg:250)[󰭼](bold white) \
$all[╰─](fg:250)$character"""

# Drop ugly default prompt characters
[character]
success_symbol = "[╼](250)"
error_symbol = "[╼](250)"

# ---

[os]
format = '[$symbol](bold white) '
disabled = true

[os.symbols]
Windows = ''
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

# ---

# Shows the username
[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = false

# Shows current directory
[directory]
# truncation_length = 1
# home_symbol = '󰋜 ~'
home_symbol = '󰋜'
read_only_style = '197'
read_only = '  '
format = '[$path]($style)[$read_only]($read_only_style) '

# Shows current git branch
[git_branch]
format = '\[[$symbol$branch]($style)\]'

# Shows current git status
[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
conflicted = '󰞇(bold red) '

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[nodejs]
format = ' []($style)'

[ruby]
format = ' []($style)'

[lua]
format = '\[[$symbol($version)]($style)\]'
disabled = true


[custom.cf_vault]
description = "Displays Cloudflare Vault session role and remaining duration"
command = "~/.config/starship_cf_vault.sh"
when = "test -n \"$CLOUDFLARE_SESSION_EXPIRY\" && test -n \"$CLOUDFLARE_VAULT_SESSION\""
format = '\[[($output)]($style)\]'
shell = "bash"
